### ISSUE TITLE
Pouvoir écraser les paramètres par défaut d'initialisation

### ISSUE THREAD

**Issue by oTiMo** [ouvrages/tarteaucitron#1]
On pourrait par exemple les passer dans une key "options" : 

```
<%= tarteaucitron(:google_analytics => "UA-XXXXXX-XX", :google_plus => true, :options => {:showAlertSmall => false}) %>
```

**Comment by Antoine-C** [comment]
https://github.com/ouvrages/tarteaucitron/pull/3

**Comment by sigmike** [comment]
Il reste juste un truc: mettre les options en indifferent_access pour qu'on puisse passer un symbol comme dans l'exemple donné.

**Comment by oTiMo** [comment]
C'est fait sur master commit 7e73c79a88c24dd2f228abd61815aebdcdeb5a6b
