### ISSUE TITLE
helper pour créer le lien qui affiche la boite de dialogue

### ISSUE THREAD

**Issue by oTiMo** [ouvrages/tarteaucitron#2]
Un helper qui génère automatiquement le lien :

```
 <a href="javascript:tarteaucitron.userInterface.openPanel();">Gestion des cookies</a>
```

Idéalement on doit pouvoir customiser le texte.

**Comment by Antoine-C** [comment]
https://github.com/ouvrages/tarteaucitron/pull/5

**Comment by sigmike** [comment]
Le helper c'est `cookie_manager_link(text = "Gestion des cookies")`
