### ISSUE TITLE
Problem dowloading GeoIP.dat.gz

### ISSUE THREAD

**Issue by organicweb** [ouvrages/tarteaucitron#7]
When running bundle install, got that error

open-uri.rb:377:in `open_http': 404 Not Found (OpenURI::HTTPError)

GeoIP.dat.gz link is broken.

Ok sorry, my bad it's a GeoIP problem.

**Comment by oTiMo** [comment]
@organicweb : fixed here : a343c730957f450376202f88586c7e661260d54d

**Comment by oTiMo** [comment]
@organicweb : sorry the gem was broken again. it is fixed.
